opensync: Set ieee80211w as 2 in wpa3 mode
Telecominfraproject/wlan-ap pull request #176
Opened 2021-02-16 03:55 UTC by chaitanyagodavarthi

set ieee80211w as 2 which enables the requirement
for PMF to be mandatory for wpa3 mode.

2021-02-16 16:17 UTC, cbuschfb commented
missing SoB

2021-02-16 17:15 UTC, RickSommerville requested changes
As Chris pointed out, you missed the "signed off by".

Use "git commit --signoff".  Thanks

2021-02-16 17:15 UTC, RickSommerville commented on feeds/wlan-ap/opensync/src/platform/openwrt/src/lib/target/src/vif.c
> +	LOGN("Kimode=%s", mode);
This must go.

2021-02-17 03:32 UTC, RickSommerville commented
Merged, thank you.

2021-02-17 03:32 UTC, closed without merging